### ISSUE TITLE
[APL] Finisher condition change

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#40]
> using Backstab when Shadowblades is not up to get to 6 CP is a damage win over finishing with 5 CP.
> credits go to Dayew#2081 

**old**
>`actions+=/call_action_list,name=finish,if=combo_points>=5|(combo_points>=4&combo_points.deficit<=2&spell_targets.shuriken_storm>=3&spell_targets.shuriken_storm<=4)|(target.time_to_die<=1&combo_points>=3)`

**new**
>`actions+=/call_action_list,name=finish,if=(combo_points>=5&(buff.shadow_blades.up|buff.shadow_dance.up))|combo_points=6|(combo_points>=4&combo_points.deficit<=2&spell_targets.shuriken_storm>=3&spell_targets.shuriken_storm<=4)|(target.time_to_die<=1&combo_points>=3)`

**Comment by Mystler** [comment]
**Edited**
Simpler version of the same change, but a DS check should be added:
> `
actions+=/call_action_list,name=finish,if=combo_points>=5+(talent.deeper_stratagem.enabled&!buff.shadow_blades.up)|(combo_points>=4&combo_points.deficit<=2&spell_targets.shuriken_storm>=3&spell_targets.shuriken_storm<=4)|(target.time_to_die<=1&combo_points>=3)
`

No need to check for Shadow Dance in that line because APL will be in stealthed list anyway.

**Comment by Mystler** [comment]
Thanks. Implemented in simulationcraft/simc@57a47afe6405f1a569e00aa2d2002d28da6647f2.
