### ISSUE TITLE
Gear improvements for the T21 Outlaw profile

### ISSUE THREAD

**Issue by ryan10c** [Ravenholdt-TC/Issues#75]
I was playing around with the outlaw profile used in the combinator. I found some minor improvements to the marked for death build, and some major improvements for the slice and dice build (will need a gear override in the combinator similar to the how exsanguinate has one). Here are the sims with the new gear showing the improvement.

[Updated Outlaw Profile.zip](https://github.com/Ravenholdt-TC/Rogue/files/1544464/Updated.Outlaw.Profile.zip)

Also note, that the Slice and Dice build benefits significantly more from the empowered pantheon proc, so we should set that as the default profile to show up in the stack at simulationcraft.com. Here are the same sims as above, but with 15 pantheon users.

[Updated Outlaw Profile w 15 pantheon users.zip](https://github.com/Ravenholdt-TC/Rogue/files/1544468/Updated.Outlaw.Profile.w.15.pantheon.users.zip)

**Comment by Mystler** [comment]
Thanks a lot for your input. I have updated the SimC default profiles and the profile for Hero Damage accordingly. 👍 

About the stacked chart: The SimC team decided that there should only be one profile for each spec. The profiles for Exsg, SnD and MfD exist and are maintained but not shown in the Raid sims. I have decided to keep RtB Outlaw in that list because it performs better without the pantheon empowerment from the Raid sim and is likely more common. I am aware this is something for discussion, but in the end people have to make their own decision about RtB/SnD concerning their own char anyway.
